name: Deploy all docker images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run tests
        run: |
          docker build -t etenity/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true etenity/react-test npm test

      - name: Build Docker images
        run: |
          docker build -t etenity/multi-client ./client
          docker build -t etenity/multi-nginx ./nginx
          docker build -t etenity/multi-server ./server
          docker build -t etenity/multi-worker ./worker

      - name: Push Docker images
        run: |
          docker push etenity/multi-client
          docker push etenity/multi-nginx
          docker push etenity/multi-server
          docker push etenity/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-654654330473
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip